baseurl                                         = "https://ishabbi.tech/"
title                                           = "Ish's Blog"
theme                                           = "hugo-coder"
languagecode                                    = "en"
defaultcontentlanguage                          = "en"

enableEmoji                                     = true
canonifyurls                                    = true

enableRobotsTXT                                 = true

googleAnalytics                                 = "G-NLSP1WW1RZ"

[pagination]
pagerSize                                       = 20

[markup.highlight]
style                                           = "monokai"

[markup.goldmark.renderer]
unsafe                                          = true

[taxonomies]
  category                                      = "categories"
  series                                        = "series"
  tag                                           = "tags"
  author                                        = "authors"

[params]
    author                                      = "Ish Abbi"
    description                                 = "Welcome to Ish's blog. Find interesting articles and snippets about testing, software engineering and many more."
    keywords                                    = "blog,developer,personal,testing,automation"
    info                                        = "Full Stack Tester, Blogger and Musician"
    avatarurl                                   = "images/820535.png"

    featuredImage                               = "/images/blog-image-of-universe.jpg"

    faviconSVG                                  = "/icons/favicon.ico"
    favicon_32                                  = "/icons/favicon-32x32.png"
    favicon_16                                  = "/icons/favicon-16x16.png"

    footercontent                               = "The scariest paths often lead to the most exciting places"

    dateformat                                  = "January 2, 2006"

    hideCredits                                 = true
    hideCopyright                               = false
    since                                       = 2019
    math                                        = true
    katex                                       = true

    rtl                                         = false

    hideColorSchemeToggle                       = true

    # Specify light/dark colorscheme
    colorscheme                                 = "auto"

    # Series see also post count
    maxSeeAlsoItems                             = 5

    # Custom CSS
    custom_css                                  = []

    # Custom JS
    custom_js                                   = []

[[params.social]]
    name                                        = "Github"
    icon                                        = "fa-brands fa-github fa-2x"
    weight                                      = 1
    url                                         = "https://github.com/rookieInTraining/"
[[params.social]]
    name                                        = "Twitter"
    icon                                        = "fa-brands fa-x-twitter fa-2x"
    weight                                      = 3
    url                                         = "https://twitter.com/ish_abbi/"
[[params.social]]
    name                                        = "LinkedIn"
    icon                                        = "fa-brands fa-linkedin fa-2x"
    weight                                      = 4
    url                                         = "https://www.linkedin.com/in/ish-abbi/"
[[params.social]]
    name                                        = "Medium"
    icon                                        = "fa-brands fa-medium fa-2x"
    weight                                      = 5
    url                                         = "https://medium.com/@ishabbi"
[[params.social]]
    name                                        = "Stackoverflow"
    icon                                        = "fa-brands fa-stack-overflow fa-2x"
    weight                                      = 5
    url                                         = "https://stackoverflow.com/users/3762268/techrookie89"

[params.csp]
    childsrc                                    = ["'self'"]
    fontsrc                                     = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/", "https://rookieintraining.github.io/"]
    formaction                                  = ["'self'"]
    framesrc                                    = ["'self'", "https://comments.app", "https://rookieintraining.github.io/", "https://topmate.io"]
    imgsrc                                      = ["'self'", "https://*.googletagmanager.com", "https://rookieintraining.github.io/"]
    objectsrc                                   = ["'none'"]
    stylesrc                                    = ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com/", "https://cdn.jsdelivr.net/", "https://rookieintraining.github.io/", "https://topmate.io", "https://*.amazonaws.com"]
    scriptsrc                                   = ["'self'", "'unsafe-inline'", "https://*.google-analytics.com", "https://*.googletagmanager.com", "https://comments.app", "https://rookieintraining.github.io/", "https://topmate.io", "https://*.amazonaws.com", "https://cdn.jsdelivr.net"]
    prefetchsrc                                     = ["'self'"]
    connectsrc                                  = ["'self'", "https://*.google-analytics.com", "https://*.analytics.google.com", "https://*.googletagmanager.com", "https://rookieintraining.github.io/"]

[params.telegram]
  siteID                                        = "SctzjgQq"
  limit                                         = "10"
  height                                        = "auto"
  color                                         = ""
  dislikes                                      = ""
  outlined                                      = ""
  colorful                                      = ""
  dark                                          = ""

[languages]
    [languages.en]
        languagename                            = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name                                = "About"
            weight                              = 3
            url                                 = "aboutme/"

            [[languages.en.menu.main]]
            name                                = "Blog"
            weight                              = 2
            url                                 = "posts/"

            [[languages.en.menu.main]]
            name                                = "Contact me"
            weight                              = 5
            url                                 = "contactme/"
